config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'                                                                                                                                                                                         
  get '/search' => 'search#index', as: 'search'

  get 'search/index'

  get 'home/index'

  resources :tracks, only: [:show]
  resources :artists, only: [:show]
  resources :albums, only: [:show]
  apipie
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: '1', default: true) do
      resources :tracks, only: [:index, :show, :create, :update, :destroy]
      resources :albums, only: [:index, :show, :create, :update, :destroy]
      resources :artists,only: [:index, :show, :create, :update, :destroy]

      get "search/tracks", controller: 'tracks', action: 'search'
      get "search/albums", controller: 'albums', action: 'search'
      get "search/artists", controller: 'artists', action: 'search'

      post "albums/:album_ids/artists/:artist_ids/tracks", controller: 'tracks', action: 'create_with_album_and_artist', as: 'create_with_album_and_artist'
    end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :track_artists
  has_many :tracks, :through => :track_artists
  validates_presence_of :firstname, :lastname, :aka
  validates_uniqueness_of :aka, :scope => [:firstname,:lastname], :message => '%{value} exists already !!'
end

app/controllers/api/v1/artists_controller.rb
class Api::V1::ArtistsController <  Api::BaseController  
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def_param_group :id do
    param :id, :number, "Artist id", :required => true
  end

  def_param_group :artist_details do
    param :artist, Hash do
      param :lastname, String, "Artist lastname"
      param :firstname, String, "Artist firstname"
      param :aka, String, "Artist alias (Also Known As)"
    end
  end

  def_param_group :required_artist_details do
    param :artist, Hash do
      param :lastname, String, "Artist lastname", :required => true
      param :firstname, String, "Artist firstname", :required => true
      param :aka, String, "Artist alias (Also Known As)", :required => true
    end
  end

  resource_description do
    short 'Site Artists'
    formats ['json']
    error 404, "Record Not Found"
    error 422, "Unprocessable Entity"
  end

  api :GET, '/search/artists', "Get all artists filtered by search parameters"
  param :firstname, String, "Artist firstname"
  param :lastname, String, "Artist lastname"
  # GET /api/search/artists
  def search
    @artists = Artist.where("firstname like :firstname AND lastname like :lastname AND aka like :aka",firstname: "%#{params[:firstname]}%",lastname: "%#{params[:lastname]}%",aka: "%#{params[:aka]}%")
    
    render json: @artists
  end

  api :GET, '/artists', "Get all artists"
  # GET /api/artists
  def index
    @artists = Artist.all
    
    render json: @artists
  end

  api :GET, "/artists/:id", "Show artist details by :id"
  param_group :id
  # GET /api/artists/1
  def show
    render json: @artist
  end

  api :POST, "/artists", "Create an artist"
  param_group :required_artist_details
  # POST /api/artists
  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      render json: @artist, status: :created
    else
      render json: @artist.errors, status: :unprocessable_entity
    end
  end

  api :PUT, "/artists/:id", "Update artist details"
  param_group :id
  param_group :artist_details
  # PATCH/PUT /api/artists/1
  def update
    if @artist.update(artist_params)
      head :no_content
    else
      render json: @artist.errors, status: :unprocessable_entity
    end
  end

  api :DELETE, "/artists/:id", "Delete artist by :id"
  param_group :id
  # DELETE /api/artists/1
  def destroy
    @artist.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      begin
        @artist = Artist.find(params[:id])
      rescue ActiveRecord::RecordNotFound  => e
        render :json => {error: 'record not found'}, status: :not_found
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:firstname, :lastname, :aka)
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show]

  # GET /artists/1
  # GET /artists/1.json
  def show
    @tracks = @artist.tracks
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
      @artists = [@artist]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:firstname, :lastname, :aka)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_index.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:aka) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.id, artist_path(artist) %></td>
        <td><%= artist.firstname %></td>
        <td><%= artist.lastname %></td>
        <td><%= artist.aka %></td>
        <td><%=l artist.created_at %></td>
        <td>
           <%= link_to t('.show', :default => t("helpers.links.show")),
                      artist_path(artist), :class => 'btn btn-success btn-xs' %>
        </td>
      </tr>
    <% end %>
    <% if @artists_message %> 
      <tr><td colspan=42 class='text-center'><%= @artists_message %></td></tr>
    <% end %>
  </tbody>
</table>

app/views/artists/index.html.erb
<%= render 'index' %>

app/views/artists/show.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %> Details</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:aka) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.id, artist_path(artist) %></td>
        <td><%= artist.firstname %></td>
        <td><%= artist.lastname %></td>
        <td><%= artist.aka %></td>
        <td><%=l artist.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'tracks/index' %>

<%= link_to 'Go Back', :back, class: 'btn btn-primary btn-large pull-right' %>