config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'                                                                                                                                                                                         
  get '/search' => 'search#index', as: 'search'

  get 'search/index'

  get 'home/index'

  resources :tracks, only: [:show]
  resources :artists, only: [:show]
  resources :albums, only: [:show]
  apipie
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: '1', default: true) do
      resources :tracks, only: [:index, :show, :create, :update, :destroy]
      resources :albums, only: [:index, :show, :create, :update, :destroy]
      resources :artists,only: [:index, :show, :create, :update, :destroy]

      get "search/tracks", controller: 'tracks', action: 'search'
      get "search/albums", controller: 'albums', action: 'search'
      get "search/artists", controller: 'artists', action: 'search'

      post "albums/:album_ids/artists/:artist_ids/tracks", controller: 'tracks', action: 'create_with_album_and_artist', as: 'create_with_album_and_artist'
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	@artists = @albums = @tracks = []

    if params[:query]
      if params[:query].length < 3
       flash.now[:error] = "Please enter a more specific search query... (at least 3 characters)"
      else
        @albums = Album.where("LOWER(title) like LOWER(:title)",title: "%#{params[:query]}%")
    	@tracks = Track.where("LOWER(title) like LOWER(:title)",title: "%#{params[:query]}%")
    	@artists = Artist.where("LOWER(firstname) like LOWER(:query) OR LOWER(lastname) like LOWER(:query) OR LOWER(aka) like LOWER(:query)",query: "%#{params[:query]}%")
      end
    end
    @tracks_message = "#{@tracks.count} track(s) found..."
    @artists_message = "#{@artists.count} artist(s) found..."
    @albums_message = "#{@albums.count} album(s) found..."
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<% @title = "Search" %>
<div>
<row>
<div>

<%= form_tag search_path, :method => 'get', :enforce_utf8 => false do %>
<div class="col-lg-11 col-sm-11">
  <%= text_field_tag :query, params[:query], placeholder: 'Enter a search query...', :class => 'form-control', :autofocus => true %>
  </div>
  <div class="col-lg-1 col-sm-1">
  <%= submit_tag(value = "Search", :class => "btn btn-primary btn-mini" ) %>
  </div>
<% end %>
</div>
</row>
</div>
</br>
<%= render 'artists/index' %>
<%= render 'albums/index' %>
<%= render 'tracks/index' %>