config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'                                                                                                                                                                                         
  get '/search' => 'search#index', as: 'search'

  get 'search/index'

  get 'home/index'

  resources :tracks, only: [:show]
  resources :artists, only: [:show]
  resources :albums, only: [:show]
  apipie
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: '1', default: true) do
      resources :tracks, only: [:index, :show, :create, :update, :destroy]
      resources :albums, only: [:index, :show, :create, :update, :destroy]
      resources :artists,only: [:index, :show, :create, :update, :destroy]

      get "search/tracks", controller: 'tracks', action: 'search'
      get "search/albums", controller: 'albums', action: 'search'
      get "search/artists", controller: 'artists', action: 'search'

      post "albums/:album_ids/artists/:artist_ids/tracks", controller: 'tracks', action: 'create_with_album_and_artist', as: 'create_with_album_and_artist'
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :album_tracks
  has_many :tracks, :through => :album_tracks
  has_many :artists, :through => :track_artists
  validates_presence_of :title, :year
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show]

  # GET /albums/1
  # GET /albums/1.json
  def show
    @tracks = @album.tracks
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
      @albums = [@album]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :year)
    end
end

app/controllers/api/v1/albums_controller.rb
class Api::V1::AlbumsController < Api::BaseController  
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def_param_group :id do
    param :id, :number, "Album id", :required => true
  end

  def_param_group :album_details do
    param :album, Hash do
      param :title, String, "Album title"
      param :year, :number, "Album year"
    end
  end

  def_param_group :required_album_details do
    param :album, Hash do
      param :title, String, "Album title", :required => true
      param :year, :number, "Album year", :required => true
    end
  end

  resource_description do
    short 'Site Albums'
    formats ['json']
    error 404, "Record Not Found"
    error 422, "Unprocessable Entity"
  end

  api :GET, '/search/albums', "Get all albums filtered by search parameters"
  param :title, String, "Album title"
  # GET /api/search/albums
  def search
    @albums = Album.where("title like :title",title: "%#{params[:title]}%")
    
    render json: @albums
  end

  api :GET, '/albums', "Get all albums"
  # GET /api/albums
  def index
    @albums = Album.all
    
    render json: @albums
  end

  api :GET, "/albums/:id", "Show album details by :id"
  param_group :id
  # GET /api/albums/1
  def show
    render json: @album
  end

  api :POST, "/albums", "Create an album"
  param_group :required_album_details
  # POST /api/albums
  def create
    @album = Album.new(album_params)

    if @album.save
      render json: @album, status: :created
    else
      render json: @album.errors, status: :unprocessable_entity
    end
  end

  api :PUT, "/albums/:id", "Update album details"
  param_group :id
  param_group :album_details
  # PATCH/PUT /api/albums/1
  def update
    if @album.update(album_params)
      head :no_content
    else
      render json: @album.errors, status: :unprocessable_entity
    end
  end

  api :DELETE, "/albums/:id", "Delete album by :id"
  param_group :id
  # DELETE /api/albums/1
  def destroy
    @album.destroy
    
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      begin
        @album = Album.find(params[:id])
      rescue ActiveRecord::RecordNotFound  => e
         render :json => {error: 'record not found'}, status: :not_found
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :year)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_index.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to album.id, album_path(album) %></td>
        <td><%= album.title %></td>
        <td><%= album.year %></td>
        <td><%=l album.created_at %></td>
        <td>
           <%= link_to t('.show', :default => t("helpers.links.show")),
                      album_path(album), :class => 'btn btn-success btn-xs' %>
        </td>
      </tr>
    <% end %>
    <% if @albums_message %> 
      <tr><td colspan=42 class='text-center'><%= @albums_message %></td></tr>
    <% end %>
  </tbody>
</table>

app/views/albums/index.html.erb
<%= render 'index' %>

app/views/albums/show.html.erb
<%- model_class = Album -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %> Details</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to album.id, album_path(album) %></td>
        <td><%= album.title %></td>
        <td><%= album.year %></td>
        <td><%=l album.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'tracks/index' %>

<%= link_to 'Go Back', :back, class: 'btn btn-primary btn-large pull-right' %>